plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		url 'https://repo.hypixel.net/repository/Hypixel'
	}
	maven {
		url 'https://jitpack.io'
	}
	mavenCentral()
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:intermediary:${project.minecraft_version}"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:0.138.0+1.21.10"

	modImplementation include ('org.graalvm.polyglot:polyglot:23.1.0')
	modImplementation include("net.hypixel:mod-api:1.0.1")
	modImplementation include ('com.github.JnCrMx:discord-game-sdk4j:v0.5.5')

	modApi include("org.lwjgl:lwjgl-nanovg:3.3.3")
	modRuntimeOnly include("org.lwjgl:lwjgl-nanovg:3.3.3:natives-linux")
	modRuntimeOnly include("org.lwjgl:lwjgl-nanovg:3.3.3:natives-linux-arm64")
	modRuntimeOnly include("org.lwjgl:lwjgl-nanovg:3.3.3:natives-windows")
	modRuntimeOnly include("org.lwjgl:lwjgl-nanovg:3.3.3:natives-windows-arm64")
	modRuntimeOnly include("org.lwjgl:lwjgl-nanovg:3.3.3:natives-macos")
	modRuntimeOnly include("org.lwjgl:lwjgl-nanovg:3.3.3:natives-macos-arm64")
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
